---
- name: Install Filebeat specific verion in Windows
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ filebeat_package }}"
    state: "{{ filebeat_package_state }}"
    version: "{{ filebeat_windows_version }}"
  when: filebeat_windows_version != 'latest'

- name: Install Filebeat latest verion in Windows
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ filebeat_package }}"
    state: 'latest'
  when: filebeat_windows_version == 'latest'

- name: Copy Filebeat configuration.
  ansible.windows.win_template:
    src: "{{ filebeat_template }}"
    dest: "{{ filebeat_windows_configdir }}/filebeat.yml"
  notify: restart filebeat windows

- name: Ensure Filebeat SSL key pair directory exists.
  ansible.windows.win_file:
    path: "{{ filebeat_ssl_dir }}"
    state: directory
  when: filebeat_ssl_key_file | default(false)

- name: Copy SSL key and cert for filebeat.
  ansible.windows.win_copy:
    src: "{{ item }}"
    dest: "{{ filebeat_ssl_dir }}/{{ item | basename }}"
  with_items:
    - "{{ filebeat_ssl_key_file }}"
    - "{{ filebeat_ssl_certificate_file }}"
  notify: restart filebeat windows
  when:
    - filebeat_ssl_key_file | default(false)
    - filebeat_ssl_certificate_file | default(false)
