---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Install test dependencies (RedHat).
      ansible.builtin.package:
        name: which
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install test dependencies.
      ansible.builtin.package:
        name: curl
        state: present

    - name: Set the java_packages variable (Ubuntu).
      ansible.builtin.set_fact:
        java_packages:
          - openjdk-8-jdk
      when: ansible_distribution == 'Ubuntu'

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.elasticsearch
    - role: geerlingguy.logstash
    - role: geerlingguy.filebeat
