---
- name: Converge
  hosts: all
  become: true
  vars:
    filebeat_version: 8.x
    filebeat_create_config: false  # Skip config creation for repository testing

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Set the java_packages variable (Debian/Ubuntu).
      set_fact:
        java_packages:
          - openjdk-11-jdk
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.java
      when: ansible_os_family == 'Debian'
    - role: ansible-role-filebeat

  post_tasks:
    - name: Verify DEB822 repository exists for systems using DEB822 format
      stat:
        path: /etc/apt/sources.list.d/elasticsearch.sources
      register: deb822_repo
      when: 
        - ansible_os_family == 'Debian'
        - filebeat_repo_format == 'deb822' or (filebeat_repo_format == 'auto' and ((ansible_distribution == "Debian" and ansible_distribution_major_version | int >= 12) or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 22)))

    - name: Assert DEB822 repository exists when expected
      assert:
        that:
          - deb822_repo.stat.exists
        msg: "DEB822 repository file should exist at /etc/apt/sources.list.d/elasticsearch.sources"
      when: 
        - ansible_os_family == 'Debian'
        - filebeat_repo_format == 'deb822' or (filebeat_repo_format == 'auto' and ((ansible_distribution == "Debian" and ansible_distribution_major_version | int >= 12) or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 22)))

    - name: Verify traditional repository does not exist when using DEB822
      shell: grep -r "artifacts.elastic.co" /etc/apt/sources.list.d/*.list || true
      register: traditional_repo_check
      changed_when: false
      when: 
        - ansible_os_family == 'Debian'
        - filebeat_cleanup_old_sources
        - filebeat_repo_format == 'deb822' or (filebeat_repo_format == 'auto' and ((ansible_distribution == "Debian" and ansible_distribution_major_version | int >= 12) or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 22)))

    - name: Assert old traditional repositories are cleaned up
      assert:
        that:
          - traditional_repo_check.stdout == ""
        msg: "Traditional repository entries should be cleaned up when using DEB822 format"
      when: 
        - ansible_os_family == 'Debian'
        - filebeat_cleanup_old_sources
        - filebeat_repo_format == 'deb822' or (filebeat_repo_format == 'auto' and ((ansible_distribution == "Debian" and ansible_distribution_major_version | int >= 12) or (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 22)))

    - name: Verify filebeat package is installable
      package:
        name: filebeat
        state: present
      when: ansible_os_family == 'Debian'
